### ISSUE TITLE
memory error when computing pairwise distances

### ISSUE THREAD

**Issue by adescoeudres** [raphael-group/belayer#1]
Hi, 
I am trying to run Belayer on a DLPFC sample (Visium), where the data is read from .csv files instead of the standard Visium output folder. The command I am using is:
`python belayer.py -s counts.csv coords.csv -m L -l 7 -o belayer --precomputing`
However, this fails with the following error message: 
`numpy.core._exceptions._ArrayMemoryError: Unable to allocate 212. GiB for an array with shape (168541, 168541) and data type int64`
The offending operation is `y_dist = self.y[None,:] - self.y[:,None]`, in compute_pairwise_distance(). 
Do you know how I might prevent or fix this? 
Thanks in advance!

**Comment by Congm12** [comment]
It's likely that there is something wrong with the input format. We updated the parsing code a little and added an example DLPFC sample in `dlpfc_example`. The expected log of running on this example is:
```
python src/belayer.py -s dlpfc_example/sample_151508.csv.gz dlpfc_example/sample_151508_position.csv -m L -l 6 -o test --precomputing
2022-11-16 21:41:55 - INFO - indir=None
2022-11-16 21:41:55 - INFO - stfiles=['dlpfc_example/sample_151508.csv.gz', 'dlpfc_example/sample_151508_position.csv']
2022-11-16 21:41:55 - INFO - mode=L
2022-11-16 21:41:55 - INFO - nlayers=6
2022-11-16 21:41:55 - INFO - approximate boundaries file=None
2022-11-16 21:41:55 - INFO - outprefix=test
2022-11-16 21:41:55 - INFO - platform=Visium
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 204/204 [00:33<00:00,  6.16it/s]
2022-11-16 21:42:45 - INFO - There are 140117502 tuples of boundary end points.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 204/204 [00:00<00:00, 35699.18it/s]
2022-11-16 21:42:45 - INFO - There are 41412 triples of boundary end points for half circle regions.
```
In addition, we don't recommend running commandline belayer in `--precomputing` mode, because the precomputing takes a long time. Two alternative ways are (1) setting `-m R` for rotated axis-aligned tissue; (2) set up multiple slurm jobs to precompute the likelihoods in parallel, see the comments in [jupyter notebook tutorial](https://github.com/raphael-group/belayer/blob/main/tutorial.ipynb) "Step 1: pre-compute losses for all combinations of linear boundaries".

**Comment by adescoeudres** [comment]
Thanks a lot for the quick answer. My problem turned out to be solved by providing belayer with the array coordinates instead of pixel coordinates. 

Also, thanks for the information about the precomputing taking a long time and for the link.
